### ISSUE TITLE
Incorrect Token in onMachineUnclocked Function

### ISSUE THREAD

**Issue by wcchristian** [tharakadesilva/SlackUserPresenceManager#1]
Looks like Tharaka's token was left in the string for the http request in the onMachineUnlocked method. Just wondering if this should be converted into using the getSlackToken method as the onMachineLocked method uses.

@tharakadesilva what are your thoughts on this. I'm not very experienced with this so I don't know if it is an actual bug or not. ;)

I'll write up a PR for the fix, feel free to decline and close this if it is not an issue.

**Comment by tharakadesilva** [comment]
yup. I left my token in lol! Merged your PR.

**Comment by tharakadesilva** [comment]
#2

**Comment by tharakadesilva** [comment]
#2
